import "./globals.css"
import type { Metadata } from "next"
import { geistSans, geistMono, rustico } from "@/lib/fonts"
import { cn } from "@/lib/utils"

import { ThemeProvider } from "@/components/theme/theme-provider"
import { TooltipProvider } from "@/components/ui/tooltip"
import { FadeInStagger } from "@/components/ui/animations/fade-in"
import { ThemeToggle } from "@/components/theme/theme-toggle"
import { Footer } from "@/components/sections/footer"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={cn(geistSans.variable, geistMono.variable, rustico.variable)}
      suppressHydrationWarning
    >
      <body>
        <ThemeProvider>
          <TooltipProvider>
            <FadeInStagger>
              <main className="mx-auto w-full max-w-3xl space-y-14 px-4 py-16 sm:px-6 sm:py-24">
                {children}
              </main>
              <div className="fixed right-4 bottom-4 z-50">
                <ThemeToggle />
              </div>
              <Footer />
            </FadeInStagger>
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
